ZSH=$HOME/dotfiles/zsh/oh-my-zsh
ZSH_THEME="robbyrussell"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-extras git-flow mvn rails ruby)

source $ZSH/oh-my-zsh.sh

export TERM="xterm-256color"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_40.jdk/Contents/Home

export PYTHONPATH=/usr/local/lib/python2.7/site-packages/:$PYTHONPATH

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
[[ -s $HOME/.pythonbrew/etc/bashrc ]] && source $HOME/.pythonbrew/etc/bashrc

### Added by the Heroku Toolbelt
export PATH="/Applications/Android\ Studio.app/sdk/platform-tools:$PATH"
#### ADDED NPM 
export PATH="/usr/local/share/npm/bin:/Users/jwils/dotfiles/bin:/Users/jwils/dotfiles/clover-bin":$PATH
alias rake="noglob rake"
export ANDROID_HOME=/Applications/Android\ Studio.app/sdk/

source dotfiles/zsh/aliases.sh

#source `brew --prefix git`/etc/bash_completion.d/git-completion.bash
